version: '3'
services:
  sonarqube:
    image: sonarqube:9.9.3-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonarqube
  db: 
     image: postgres
     environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
     volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
     networks:
       - sonarqube
volumes:
  sonarqube_conf: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  postgresql: {}
  postgresql_data: {}    

networks:
  sonarqube:
    name: sonarqube
    driver: bridge
